/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package práctica3;

import java.util.Random;
import javax.swing.ImageIcon;

/**
 *
 * @author usuario
 */
public class Práctica3 extends javax.swing.JFrame {
    //Creación de un objeto Random.
    Random generadorLetras = new Random();
    
    //Declaración de las principales variables.
    String cadenaLetras;
    String cadenaLetras16; 
    int numSerieImagenes = 4;
    int contadorAciertos;
    /**
     * Creates new form Práctica3
     */
    public Práctica3() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jToggleButton1 = new javax.swing.JToggleButton();
        jToggleButton2 = new javax.swing.JToggleButton();
        jToggleButton3 = new javax.swing.JToggleButton();
        jToggleButton4 = new javax.swing.JToggleButton();
        jToggleButton5 = new javax.swing.JToggleButton();
        jToggleButton6 = new javax.swing.JToggleButton();
        jToggleButton7 = new javax.swing.JToggleButton();
        jToggleButton8 = new javax.swing.JToggleButton();
        jToggleButton9 = new javax.swing.JToggleButton();
        jToggleButton10 = new javax.swing.JToggleButton();
        jToggleButton11 = new javax.swing.JToggleButton();
        jToggleButton12 = new javax.swing.JToggleButton();
        jToggleButton13 = new javax.swing.JToggleButton();
        jToggleButton14 = new javax.swing.JToggleButton();
        jToggleButton15 = new javax.swing.JToggleButton();
        jToggleButton16 = new javax.swing.JToggleButton();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 185, 78));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Z.png"))); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Z.png"))); // NOI18N

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Z.png"))); // NOI18N

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Z.png"))); // NOI18N

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Z.png"))); // NOI18N

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Z.png"))); // NOI18N

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Z.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(10, 10, 10)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 185, 78));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jToggleButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Z.png"))); // NOI18N

        jToggleButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Z.png"))); // NOI18N

        jToggleButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Z.png"))); // NOI18N

        jToggleButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Z.png"))); // NOI18N

        jToggleButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Z.png"))); // NOI18N

        jToggleButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Z.png"))); // NOI18N

        jToggleButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Z.png"))); // NOI18N

        jToggleButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Z.png"))); // NOI18N

        jToggleButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Z.png"))); // NOI18N

        jToggleButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Z.png"))); // NOI18N

        jToggleButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Z.png"))); // NOI18N

        jToggleButton12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Z.png"))); // NOI18N

        jToggleButton13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Z.png"))); // NOI18N

        jToggleButton14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Z.png"))); // NOI18N

        jToggleButton15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Z.png"))); // NOI18N

        jToggleButton16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Z.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jToggleButton12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButton13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButton14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButton15))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jToggleButton8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButton9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButton10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButton11))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jToggleButton5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButton6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButton16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButton7))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jToggleButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButton4)))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jToggleButton2)
                    .addComponent(jToggleButton1)
                    .addComponent(jToggleButton3)
                    .addComponent(jToggleButton4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jToggleButton16)
                    .addComponent(jToggleButton7)
                    .addComponent(jToggleButton6)
                    .addComponent(jToggleButton5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jToggleButton11, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jToggleButton10)
                        .addComponent(jToggleButton9))
                    .addComponent(jToggleButton8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jToggleButton14)
                    .addComponent(jToggleButton15)
                    .addComponent(jToggleButton13)
                    .addComponent(jToggleButton12))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 185, 78));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jButton1.setText("Empezar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Recordar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Comprobar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("  Aciertos:");
        jLabel8.setAlignmentX(10.0F);

        jLabel9.setFont(new java.awt.Font("Arial Black", 1, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       cadenaLetras = "";
        
        for(int i=0;i<numSerieImagenes;i++){
            //generador de letras aleatorias complendidas entre la A y la P.
            int letra = generadorLetras.nextInt(16)+65;
            char letrasAleatorias = (char) letra;
            
            //Se guarda en la variable creada anteriormente (cadenaLetras) las distintas letras generadas.
            cadenaLetras += letrasAleatorias;  
            System.out.println(cadenaLetras);
        }
        
         //Deshabilitados todos los jToogleButton.
        jToggleButton1.setEnabled(false);
        jToggleButton2.setEnabled(false);
        jToggleButton3.setEnabled(false);
        jToggleButton4.setEnabled(false);
        jToggleButton5.setEnabled(false);
        jToggleButton6.setEnabled(false);
        jToggleButton7.setEnabled(false);
        jToggleButton8.setEnabled(false);
        jToggleButton9.setEnabled(false);
        jToggleButton10.setEnabled(false);
        jToggleButton11.setEnabled(false);
        jToggleButton12.setEnabled(false);
        jToggleButton13.setEnabled(false);
        jToggleButton14.setEnabled(false);
        jToggleButton15.setEnabled(false);
        jToggleButton16.setEnabled(false);
        
        //Deseleccionados todos los jToogleButton.
        jToggleButton1.setSelected(false);
        jToggleButton2.setSelected(false);
        jToggleButton3.setSelected(false);
        jToggleButton4.setSelected(false);
        jToggleButton5.setSelected(false);
        jToggleButton6.setSelected(false);
        jToggleButton7.setSelected(false);
        jToggleButton8.setSelected(false);
        jToggleButton9.setSelected(false);
        jToggleButton10.setSelected(false);
        jToggleButton11.setSelected(false);
        jToggleButton12.setSelected(false);
        jToggleButton13.setSelected(false);
        jToggleButton14.setSelected(false);
        jToggleButton15.setSelected(false);
        jToggleButton16.setSelected(false);
        
        switch(numSerieImagenes){
            case 7:
                jLabel7.setIcon(new ImageIcon(getClass().getResource("/imagenes/"+cadenaLetras.charAt(6) +".png")));
            case 6:
                jLabel6.setIcon(new ImageIcon(getClass().getResource("/imagenes/"+cadenaLetras.charAt(5) +".png")));
            case 5:
                jLabel5.setIcon(new ImageIcon(getClass().getResource("/imagenes/"+cadenaLetras.charAt(4) +".png")));           
            case 4:
                jLabel1.setIcon(new ImageIcon(getClass().getResource("/imagenes/"+cadenaLetras.charAt(0) +".png")));  
                jLabel2.setIcon(new ImageIcon(getClass().getResource("/imagenes/"+cadenaLetras.charAt(1) +".png")));
                jLabel3.setIcon(new ImageIcon(getClass().getResource("/imagenes/"+cadenaLetras.charAt(2) +".png")));
                jLabel4.setIcon(new ImageIcon(getClass().getResource("/imagenes/"+cadenaLetras.charAt(3) +".png")));
                break;
        }
        
        jToggleButton1.setIcon(new ImageIcon(getClass().getResource("/imagenes/Z.png")));            
        jToggleButton2.setIcon(new ImageIcon(getClass().getResource("/imagenes/Z.png")));            
        jToggleButton3.setIcon(new ImageIcon(getClass().getResource("/imagenes/Z.png")));            
        jToggleButton4.setIcon(new ImageIcon(getClass().getResource("/imagenes/Z.png")));            
        jToggleButton5.setIcon(new ImageIcon(getClass().getResource("/imagenes/Z.png")));            
        jToggleButton6.setIcon(new ImageIcon(getClass().getResource("/imagenes/Z.png")));            
        jToggleButton7.setIcon(new ImageIcon(getClass().getResource("/imagenes/Z.png")));            
        jToggleButton8.setIcon(new ImageIcon(getClass().getResource("/imagenes/Z.png")));            
        jToggleButton9.setIcon(new ImageIcon(getClass().getResource("/imagenes/Z.png")));            
        jToggleButton10.setIcon(new ImageIcon(getClass().getResource("/imagenes/Z.png")));            
        jToggleButton11.setIcon(new ImageIcon(getClass().getResource("/imagenes/Z.png")));            
        jToggleButton12.setIcon(new ImageIcon(getClass().getResource("/imagenes/Z.png")));            
        jToggleButton13.setIcon(new ImageIcon(getClass().getResource("/imagenes/Z.png")));            
        jToggleButton14.setIcon(new ImageIcon(getClass().getResource("/imagenes/Z.png")));            
        jToggleButton15.setIcon(new ImageIcon(getClass().getResource("/imagenes/Z.png")));            
        jToggleButton16.setIcon(new ImageIcon(getClass().getResource("/imagenes/Z.png")));
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        cadenaLetras16 = "";
        do{
            //generador de 16 letras complendidas entre la A y la P.
           int contador = 1;
            while(cadenaLetras16.indexOf(cadenaLetras16.charAt(contador)) == -1){
                char letrasSinRepetir = (char)(generadorLetras.nextInt(16)+65);
                
                //Se guarda en la variable creada anteriormente (cadenaLetras16) las distintas letras generadas.
                cadenaLetras16 += letrasSinRepetir;
                contador++;
              }
            
            System.out.println(cadenaLetras16);
            
        }while(cadenaLetras16.length()<16);
        
        //Habilitados todos los jToogleButton.
        jToggleButton1.setEnabled(true);
        jToggleButton2.setEnabled(true);
        jToggleButton3.setEnabled(true);
        jToggleButton4.setEnabled(true);
        jToggleButton5.setEnabled(true);
        jToggleButton6.setEnabled(true);
        jToggleButton7.setEnabled(true);
        jToggleButton8.setEnabled(true);
        jToggleButton9.setEnabled(true);
        jToggleButton10.setEnabled(true);
        jToggleButton11.setEnabled(true);
        jToggleButton12.setEnabled(true);
        jToggleButton13.setEnabled(true);
        jToggleButton14.setEnabled(true);
        jToggleButton15.setEnabled(true);
        jToggleButton16.setEnabled(true);
        
        //Se muestra en pantalla las distintas imágenes según la letra generada.
        jToggleButton1.setIcon(new ImageIcon(getClass().getResource("/imagenes/"+cadenaLetras16.charAt(0) +".png")));
        jToggleButton2.setIcon(new ImageIcon(getClass().getResource("/imagenes/"+cadenaLetras16.charAt(1) +".png")));
        jToggleButton3.setIcon(new ImageIcon(getClass().getResource("/imagenes/"+cadenaLetras16.charAt(2) +".png")));
        jToggleButton4.setIcon(new ImageIcon(getClass().getResource("/imagenes/"+cadenaLetras16.charAt(3) +".png")));
        jToggleButton5.setIcon(new ImageIcon(getClass().getResource("/imagenes/"+cadenaLetras16.charAt(4) +".png")));
        jToggleButton6.setIcon(new ImageIcon(getClass().getResource("/imagenes/"+cadenaLetras16.charAt(5) +".png")));
        jToggleButton7.setIcon(new ImageIcon(getClass().getResource("/imagenes/"+cadenaLetras16.charAt(6) +".png")));
        jToggleButton8.setIcon(new ImageIcon(getClass().getResource("/imagenes/"+cadenaLetras16.charAt(7) +".png")));
        jToggleButton9.setIcon(new ImageIcon(getClass().getResource("/imagenes/"+cadenaLetras16.charAt(8) +".png")));
        jToggleButton10.setIcon(new ImageIcon(getClass().getResource("/imagenes/"+cadenaLetras16.charAt(9) +".png")));
        jToggleButton11.setIcon(new ImageIcon(getClass().getResource("/imagenes/"+cadenaLetras16.charAt(10) +".png")));
        jToggleButton12.setIcon(new ImageIcon(getClass().getResource("/imagenes/"+cadenaLetras16.charAt(11) +".png")));
        jToggleButton13.setIcon(new ImageIcon(getClass().getResource("/imagenes/"+cadenaLetras16.charAt(12) +".png")));
        jToggleButton14.setIcon(new ImageIcon(getClass().getResource("/imagenes/"+cadenaLetras16.charAt(13) +".png")));
        jToggleButton15.setIcon(new ImageIcon(getClass().getResource("/imagenes/"+cadenaLetras16.charAt(14) +".png")));
        jToggleButton16.setIcon(new ImageIcon(getClass().getResource("/imagenes/"+cadenaLetras16.charAt(15) +".png")));
        
        //Asignamos la imagen Z.png a cada uno de los jLabel que aparecen el la parte superior de la pantalla resultante.
        jLabel1.setIcon(new ImageIcon(getClass().getResource("/imagenes/Z.png")));            
        jLabel2.setIcon(new ImageIcon(getClass().getResource("/imagenes/Z.png")));            
        jLabel3.setIcon(new ImageIcon(getClass().getResource("/imagenes/Z.png")));            
        jLabel4.setIcon(new ImageIcon(getClass().getResource("/imagenes/Z.png")));            
        jLabel5.setIcon(new ImageIcon(getClass().getResource("/imagenes/Z.png")));            
        jLabel6.setIcon(new ImageIcon(getClass().getResource("/imagenes/Z.png")));            
        jLabel7.setIcon(new ImageIcon(getClass().getResource("/imagenes/Z.png"))); 
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        contadorAciertos=0;
        /*Preguntamos si los jjToggleButtonx están seleccionados y además, el carácter
         contiene cada uno de ellos coincide con alguno de los caracteres de la serie principal, 
         es decir, la que se encuentra en la parte superior.
         Si todo ha sido así el contador de aciertos si incrementará. En caso contrario, el botón 
         estará deshabilitado.*/ 
        
        if(jToggleButton1.isSelected() && cadenaLetras.indexOf(cadenaLetras16.charAt(0))!=-1) {
            contadorAciertos++;
        } else {
            jToggleButton1.setEnabled(false);
        }
                
        if(jToggleButton2.isSelected() && cadenaLetras.indexOf(cadenaLetras16.charAt(1))!=-1) {
            contadorAciertos++;
        } else {
            jToggleButton2.setEnabled(false);
        }

        if(jToggleButton3.isSelected() && cadenaLetras.indexOf(cadenaLetras16.charAt(2))!=-1) {
            contadorAciertos++;
        } else {
            jToggleButton3.setEnabled(false);
        }

        if(jToggleButton4.isSelected() && cadenaLetras.indexOf(cadenaLetras16.charAt(3))!=-1) {
            contadorAciertos++;
        } else {
            jToggleButton4.setEnabled(false);
        }

        if(jToggleButton5.isSelected() && cadenaLetras.indexOf(cadenaLetras16.charAt(4))!=-1) {
            contadorAciertos++;
        } else {
            jToggleButton5.setEnabled(false);
        }

        if(jToggleButton6.isSelected() && cadenaLetras.indexOf(cadenaLetras16.charAt(5))!=-1) {
            contadorAciertos++;
        } else {
            jToggleButton6.setEnabled(false);
        }

        if(jToggleButton7.isSelected() && cadenaLetras.indexOf(cadenaLetras16.charAt(6))!=-1) {
            contadorAciertos++;
        } else {
            jToggleButton7.setEnabled(false);
        }

        if(jToggleButton8.isSelected() && cadenaLetras.indexOf(cadenaLetras16.charAt(7))!=-1) {
            contadorAciertos++;
        } else {
            jToggleButton8.setEnabled(false);
        }

        if(jToggleButton9.isSelected() && cadenaLetras.indexOf(cadenaLetras16.charAt(8))!=-1) {
            contadorAciertos++;
        } else {
            jToggleButton9.setEnabled(false);
        }

        if(jToggleButton10.isSelected() && cadenaLetras.indexOf(cadenaLetras16.charAt(9))!=-1) {
            contadorAciertos++;
        } else {
            jToggleButton10.setEnabled(false);
        }

        if(jToggleButton11.isSelected() && cadenaLetras.indexOf(cadenaLetras16.charAt(10))!=-1) {
            contadorAciertos++;
        } else {
            jToggleButton11.setEnabled(false);
        }

        if(jToggleButton12.isSelected() && cadenaLetras.indexOf(cadenaLetras16.charAt(11))!=-1) {
            contadorAciertos++;
        } else {
            jToggleButton12.setEnabled(false);
        }

        if(jToggleButton13.isSelected() && cadenaLetras.indexOf(cadenaLetras16.charAt(12))!=-1) {
            contadorAciertos++;
        } else {
            jToggleButton13.setEnabled(false);
        }

        if(jToggleButton14.isSelected() && cadenaLetras.indexOf(cadenaLetras16.charAt(13))!=-1) {
            contadorAciertos++;
        } else {
            jToggleButton14.setEnabled(false);
        }

        if(jToggleButton15.isSelected() && cadenaLetras.indexOf(cadenaLetras16.charAt(14))!=-1) {
            contadorAciertos++;
        } else {
            jToggleButton15.setEnabled(false);
        }

        if(jToggleButton16.isSelected() && cadenaLetras.indexOf(cadenaLetras16.charAt(15))!=-1) {
            contadorAciertos++;
        } else {
            jToggleButton16.setEnabled(false);
        }
        
        //Se muestra en pantalla los aciertos obtenidos.
        jLabel9.setText(String.valueOf(contadorAciertos));
        
        //Se compara el número de aciertos con el número de imágenes.
        if(contadorAciertos == numSerieImagenes && numSerieImagenes<7) {
           //El número de imágenes se incrementará hasta llegar a 7.
            numSerieImagenes++;
        }      
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Práctica3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Práctica3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Práctica3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Práctica3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Práctica3().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton10;
    private javax.swing.JToggleButton jToggleButton11;
    private javax.swing.JToggleButton jToggleButton12;
    private javax.swing.JToggleButton jToggleButton13;
    private javax.swing.JToggleButton jToggleButton14;
    private javax.swing.JToggleButton jToggleButton15;
    private javax.swing.JToggleButton jToggleButton16;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JToggleButton jToggleButton3;
    private javax.swing.JToggleButton jToggleButton4;
    private javax.swing.JToggleButton jToggleButton5;
    private javax.swing.JToggleButton jToggleButton6;
    private javax.swing.JToggleButton jToggleButton7;
    private javax.swing.JToggleButton jToggleButton8;
    private javax.swing.JToggleButton jToggleButton9;
    // End of variables declaration//GEN-END:variables
}
